//------------------------------------------------------------------------------
// Box3D + sokol walkthrough
//
// This program has two main jobs which meet once per frame:
//
//   Box3D (CPU)                         sokol_gfx (GPU)
//   ---------------------------         -------------------------------
//   simulate bodies and collisions  -> copy transforms into a GPU buffer
//                                      draw a shadow map from the light
//                                      draw the visible scene from the camera
//
// The frame is rendered in two passes:
//
//   1. Shadow pass: render depth from the light's point of view into a texture.
//   2. Display pass: render colors from the camera and sample that depth texture
//      to decide which pixels are in shadow.
//
// Boxes and balls use GPU instancing. Their mesh is uploaded once, then a small
// transform-and-color record is supplied for every body. One draw call can
// therefore draw many copies of the same mesh.
//------------------------------------------------------------------------------

// Zig's standard library supplies assertions, math helpers, formatting, etc.
const std = @import("std");
// Generated Zig bindings for the Box3D C API.
const b3 = @import("box3d");
// Dear ImGui's C API, used for the small status/debug interface.
const ig = @import("cimgui");
// The sokol-zig package: windowing, graphics, helpers, timing, and debug UI.
const sokol = @import("sokol");
// Shader interfaces generated by sokol-shdc from src/examples/box3d.glsl.
// This gives Zig typed uniform structs and backend-specific shader descriptions.
const shd = @import("generated/box3d_shader.zig");
// Small vector and matrix types used to prepare transforms on the CPU.
const math = @import("math");

// Short aliases keep the graphics code readable. Each alias is one sokol module.
const sapp = sokol.app;
const sappimgui = sokol.appimgui; // Inspector/debug UI for sokol_app.
const sg = sokol.gfx; // Portable GPU API: buffers, images, pipelines, and draw calls.
const sgimgui = sokol.gfximgui; // Inspector/debug UI for sokol_gfx.
const sglue = sokol.glue; // Connects sokol_app's window to sokol_gfx.
const simgui = sokol.imgui; // Renders Dear ImGui through sokol_gfx.
const slog = sokol.log; // Sends sokol log messages to the console.
const sshape = sokol.shape; // Generates simple plane, box, and sphere meshes.
const stm = sokol.time; // High-resolution timing used by the profiler UI.

// Local names for the math types used most often below.
const Vec3 = math.Vec3;
const Vec4 = math.Vec4;
const Mat4 = math.Mat4;

// Capacity limits. Fixed arrays avoid allocating memory while the app is running.
const max_shapes = 1024;
// Half of the spawned bodies are boxes and half are balls. The extra slot handles
// an odd total safely.
const max_instances = max_shapes / 2 + 1;

// Dimensions shared by the physics shapes and their visible meshes.
const ground_size: f32 = 200.0;
const ball_radius: f32 = 1.0;
const box_size: f32 = 1.5;

// A shadow map is a depth texture. More pixels give sharper shadow edges but use
// more GPU memory and rendering work.
const shadow_map_size = 2048;

// Box3D recommends a fixed 60 Hz world tick with four internal solver sub-steps.
// Limiting accumulated time prevents an extended pause from causing an
// unbounded number of catch-up steps (the usual fixed-timestep "spiral of death").
const physics_tick_sec: f64 = 1.0 / 60.0;
const physics_sub_step_count: i32 = 4;
const max_frame_delta_sec: f64 = 0.25;

// Add a new box or ball four times per second.
const spawn_interval_sec: f64 = 0.25;

// Per-object data streamed from CPU memory to the GPU.
//
// xxxx/yyyy/zzzz hold the first three rows of a 4x4 transform. The final row is
// constant for an affine transform, so omitting it saves bandwidth. color.w is
// also reused as a "sleeping" flag for the debug display.
//
// `extern` gives the struct a predictable C-compatible memory layout. That is
// essential because the vertex shader reads these bytes directly.
const InstanceData = extern struct {
    xxxx: Vec4 = .{},
    yyyy: Vec4 = .{},
    zzzz: Vec4 = .{},
    color: Vec4 = .{},
};

// Four Vec4 values must occupy exactly 64 bytes. Fail at compile time if a future
// type/layout change would make the GPU interpret this memory incorrectly.
comptime {
    std.debug.assert(@sizeOf(InstanceData) == 64);
}

//------------------------------------------------------------------------------
// Orbit camera
//
// The camera is described with spherical coordinates around `center`:
// longitude turns left/right, latitude turns up/down, and distance zooms.
//------------------------------------------------------------------------------
const Camera = struct {
    // Limits prevent zooming through the subject or flipping over the poles.
    min_dist: f32 = 2.0,
    max_dist: f32 = 300.0,
    min_lat: f32 = -85.0,
    max_lat: f32 = 85.0,
    distance: f32 = 50.0,
    latitude: f32 = 25.0,
    longitude: f32 = 225.0,
    center: Vec3 = .{},
    eye_pos: Vec3 = .{},

    // Convert the camera's angles into a Cartesian direction, then place its eye
    // that many units away from the orbit center.
    fn update(self: *Camera) void {
        const lat = math.degreesToRadians(self.latitude);
        const lng = math.degreesToRadians(self.longitude);
        const direction: Vec3 = .{
            .x = @cos(lat) * @sin(lng),
            .y = @sin(lat),
            .z = @cos(lat) * @cos(lng),
        };
        self.eye_pos = Vec3.add(self.center, Vec3.scale(direction, self.distance));
    }

    // Mouse movement changes the orbit angles. Longitude wraps around a full
    // circle; latitude clamps before the top/bottom singularities.
    fn orbit(self: *Camera, dx: f32, dy: f32) void {
        self.longitude -= dx;
        if (self.longitude < 0.0) self.longitude += 360.0;
        if (self.longitude > 360.0) self.longitude -= 360.0;
        self.latitude = std.math.clamp(self.latitude + dy, self.min_lat, self.max_lat);
    }

    // Scale zoom speed by the current distance: large scenes zoom faster while
    // close-up movement remains precise.
    fn zoom(self: *Camera, delta: f32) void {
        self.distance = std.math.clamp(
            self.distance + delta * self.distance * 0.1,
            self.min_dist,
            self.max_dist,
        );
    }

    // sokol_app converts platform-specific mouse messages into portable events.
    fn handleEvent(self: *Camera, event: sapp.Event) void {
        switch (event.type) {
            // Locking the mouse hides/captures it so dragging can continue even
            // after the pointer reaches the window edge.
            .MOUSE_DOWN => if (event.mouse_button == .LEFT) sapp.lockMouse(true),
            .MOUSE_UP => if (event.mouse_button == .LEFT) sapp.lockMouse(false),
            // The wheel changes camera distance.
            .MOUSE_SCROLL => self.zoom(event.scroll_y * 0.5),
            // Relative mouse motion orbits only while the left button is held.
            .MOUSE_MOVE => if (sapp.mouseLocked()) {
                self.orbit(event.mouse_dx * 0.25, event.mouse_dy * 0.25);
            },
            else => {},
        }
    }
};

//------------------------------------------------------------------------------
// Application state
//
// Sokol resource handles are small IDs referring to objects owned by the GPU
// backend. Keeping them here makes initialization, drawing, and cleanup share the
// same resources without heap allocation.
//------------------------------------------------------------------------------
const State = struct {
    // Static mesh vertices and indices shared by the plane, box, and sphere.
    vbuf: sg.Buffer = .{},
    ibuf: sg.Buffer = .{},

    // Dynamic per-instance data, updated as Box3D bodies move.
    box_inst_buf: sg.Buffer = .{},
    ball_inst_buf: sg.Buffer = .{},

    // Each ElementRange selects one mesh inside the shared index buffer.
    shapes: struct {
        plane: sshape.ElementRange = .{},
        ball: sshape.ElementRange = .{},
        box: sshape.ElementRange = .{},
    } = .{},

    // Resources for rendering depth into the shadow map.
    shadow: struct {
        pass: sg.Pass = .{}, // Off-screen render pass targeting the depth image.
        tex_view: sg.View = .{}, // The same image viewed as a shader texture.
        sampler: sg.Sampler = .{}, // Rules for sampling/comparing shadow depth.
        inst_pipeline: sg.Pipeline = .{}, // GPU state/shader for shadow instances.
    } = .{},

    // Resources for the visible, on-screen pass.
    display: struct {
        pass_action: sg.PassAction = .{}, // How the window framebuffer is cleared.
        pipeline: sg.Pipeline = .{}, // Non-instanced pipeline for the ground.
        inst_pipeline: sg.Pipeline = .{}, // Instanced pipeline for bodies.
    } = .{},

    // Time remaining before the next body is spawned.
    spawn_timer: f64 = 0.0,
    camera: Camera = .{},

    // Values used to construct the light-space and camera-space matrices.
    light_pos: Vec3 = .{},
    light_view_proj: Mat4 = .{},
    view_proj: Mat4 = .{},

    // Measurements shown in the debug UI.
    profiling: struct {
        physics_world_step_time: u64 = 0,
        copy_transforms_time: u64 = 0,
        world_steps_per_frame: i32 = 0,
        num_awake_bodies: i32 = 0,
    } = .{},
    ui: struct {
        show_sleeping: bool = false,
    } = .{},

    // Box3D owns the simulation. Body IDs are opaque handles, like GPU handles.
    physics: struct {
        world: b3.b3WorldId = b3.b3_nullWorldId,
        ground: b3.b3BodyId = b3.b3_nullBodyId,
        // Carries time shorter than one fixed physics tick into the next frame.
        tick_accumulator_sec: f64 = 0.0,
        num_bodies: usize = 0,
        bodies: [max_shapes]b3.b3BodyId = @splat(b3.b3_nullBodyId),
    } = .{},

    // CPU-side copies of the instance records uploaded to the two GPU buffers.
    instances: struct {
        num_boxes: usize = 0,
        num_balls: usize = 0,
        boxes: [max_instances]InstanceData = @splat(.{}),
        balls: [max_instances]InstanceData = @splat(.{}),
    } = .{},
};

// One zero-initialized application state. Sokol callbacks access this global.
var state: State = .{};
// A fixed seed makes colors and impulses repeat across runs, which is useful for
// debugging and comparing native versus WASM behavior.
var random_state: u32 = 0x12345678;

//------------------------------------------------------------------------------
// sokol_app lifecycle callbacks
//------------------------------------------------------------------------------

// Called once after the window and graphics context exist.
// `callconv(.c)` gives the callback the C ABI expected by sokol_app.
fn init() callconv(.c) void {
    // Initialize timing before collecting any profiling measurements.
    stm.setup();

    // Initialize the portable graphics layer using the backend/window handles
    // supplied by sokol_app through sokol_glue.
    sg.setup(.{
        .environment = sglue.environment(),
        .logger = .{ .func = slog.func },
    });

    // Initialize optional debug inspectors and the ImGui renderer.
    sgimgui.setup(.{});
    sappimgui.setup();
    simgui.setup(.{ .logger = .{ .func = slog.func } });

    // Create the CPU simulation first, then the GPU resources used to show it.
    physicsInit();
    graphicsInit();
}

// Called once for every displayed frame.
fn frame() callconv(.c) void {
    // Turn camera controls into a current eye position.
    state.camera.update();

    // Discard excess wall time after a breakpoint, suspended tab, or long stall.
    // Catching all of it up at once could make simulation work grow without bound.
    const frame_delta_sec = @min(sapp.frameDuration(), max_frame_delta_sec);

    // Spawn bodies according to elapsed real time, not according to frame count.
    // The loop catches up the spawn schedule when one frame spans several spawn
    // intervals, subject to the same bounded frame delta used by physics.
    state.spawn_timer -= frame_delta_sec;
    while (state.spawn_timer <= 0.0 and state.physics.num_bodies < max_shapes) {
        state.spawn_timer += spawn_interval_sec;
        physicsAddBody();
    }

    // Advance Box3D, copy moved body transforms, upload them, and build matrices.
    physicsUpdate(frame_delta_sec);
    updateInstanceBuffers();
    updateMatrices();
    drawUi();

    // PASS 1: shadow map
    //
    // Render boxes and balls from the light's point of view. This pass writes
    // depth only; it does not draw visible colors to the window.
    sg.beginPass(state.shadow.pass);
    drawInstancedShadow(state.shapes.box, state.box_inst_buf, state.instances.num_boxes);
    drawInstancedShadow(state.shapes.ball, state.ball_inst_buf, state.instances.num_balls);
    sg.endPass();

    // PASS 2: visible scene
    //
    // Target the window's swapchain (the back buffer that will be presented).
    sg.beginPass(.{
        .action = state.display.pass_action,
        .swapchain = sglue.swapchain(),
    });

    // The ground is one object, so it uses the ordinary non-instanced pipeline.
    drawShapeDisplay(state.shapes.plane, Mat4.identity(), .{
        .x = 0.5,
        .y = 0.5,
        .z = 0.5,
        .w = 1.0,
    });

    // Boxes and balls each share a mesh and are drawn with one instanced call.
    drawInstancedDisplay(state.shapes.box, state.box_inst_buf, state.instances.num_boxes);
    drawInstancedDisplay(state.shapes.ball, state.ball_inst_buf, state.instances.num_balls);

    // ImGui is drawn last so the interface appears on top of the 3D scene.
    simgui.render();
    sg.endPass();

    // Submit all commands recorded this frame to the graphics backend.
    sg.commit();
}

// Called once while the application is shutting down.
fn cleanup() callconv(.c) void {
    // Release the physics world and helper systems before the graphics device.
    b3.b3DestroyWorld(state.physics.world);
    state.physics.world = b3.b3_nullWorldId;
    state.physics.ground = b3.b3_nullBodyId;
    sgimgui.shutdown();
    sappimgui.shutdown();
    simgui.shutdown();
    sg.shutdown();
}

// Called for keyboard/mouse/touch events.
fn input(event_ptr: [*c]const sapp.Event) callconv(.c) void {
    // A C callback receives a pointer; copy the first event into a Zig value.
    const event = event_ptr[0];

    // Let the inspectors and ImGui see the event first. If ImGui consumed it
    // (for example, clicking a checkbox), do not also orbit the camera.
    sappimgui.trackEvent(event);
    if (simgui.handleEvent(event)) return;
    state.camera.handleEvent(event);
}

//------------------------------------------------------------------------------
// Matrices
//
// A vertex starts in model (object-local) space. Matrix multiplication moves it
// through world space, view/camera space, and finally clip space for the GPU.
// The shaders need one view-projection matrix for the camera and another for the
// light because the same object is seen from both viewpoints.
//------------------------------------------------------------------------------
fn updateMatrices() void {
    // The light's view matrix aims from the light toward the world origin.
    const light_view = Mat4.lookAtRh(state.light_pos, .{}, .{ .y = 1.0 });

    // An orthographic projection keeps parallel light rays parallel, which
    // models a distant directional light and avoids perspective distortion.
    const light_projection = Mat4.orthoOffCenterRh(
        -100.0,
        100.0,
        -100.0,
        100.0,
        1.0,
        250.0,
    );
    // Combine view and projection once; every object's model transform is added
    // later by the relevant draw function.
    state.light_view_proj = Mat4.mul(light_view, light_projection);

    // The camera uses a perspective projection, so distant objects look smaller.
    // FOV is 60 degrees; aspect ratio prevents stretching; near/far planes bound
    // the range of depths retained by the depth buffer.
    const projection = Mat4.perspectiveFovRh(
        math.degreesToRadians(60.0),
        sapp.widthf() / sapp.heightf(),
        0.1,
        500.0,
    );
    // Aim the camera from its orbit position at the world origin.
    const view = Mat4.lookAtRh(state.camera.eye_pos, .{}, .{ .y = 1.0 });
    state.view_proj = Mat4.mul(view, projection);
}

// Upload only the active portion of each CPU instance array.
//
// These are streaming buffers: unlike the static mesh buffer, their contents
// change every frame as physics moves the objects.
fn updateInstanceBuffers() void {
    if (state.instances.num_boxes > 0) {
        sg.updateBuffer(
            state.box_inst_buf,
            sg.asRange(state.instances.boxes[0..state.instances.num_boxes]),
        );
    }
    if (state.instances.num_balls > 0) {
        sg.updateBuffer(
            state.ball_inst_buf,
            sg.asRange(state.instances.balls[0..state.instances.num_balls]),
        );
    }
}

//------------------------------------------------------------------------------
// Draw helpers
//------------------------------------------------------------------------------

// Draw all instances of one mesh into the shadow map.
fn drawInstancedShadow(shape: sshape.ElementRange, inst_buf: sg.Buffer, count: usize) void {
    // Avoid issuing an empty GPU draw command.
    if (count == 0) return;

    // Uniforms are small values constant for the whole draw call. Every shadow
    // vertex uses the same light matrix.
    const vs_params: shd.ShadowInstVsParams = .{
        .light_view_proj = state.light_view_proj,
    };

    // Bindings tell the pipeline where its shader inputs come from:
    // slot 0 = shared mesh vertices, slot 1 = per-instance transforms.
    var bindings: sg.Bindings = .{};
    bindings.vertex_buffers[0] = state.vbuf;
    bindings.vertex_buffers[1] = inst_buf;
    bindings.index_buffer = state.ibuf;

    // A pipeline packages the shaders and fixed GPU state (vertex layout, depth
    // test, culling, render-target formats). Apply it before its resources.
    sg.applyPipeline(state.shadow.inst_pipeline);
    sg.applyBindings(bindings);
    sg.applyUniforms(shd.UB_shadow_inst_vs_params, sg.asRange(&vs_params));

    // base_element and num_elements select this mesh from the shared index
    // buffer. `count` asks the GPU to repeat it for every instance record.
    sg.draw(@intCast(shape.base_element), @intCast(shape.num_elements), @intCast(count));
}

// Draw one non-instanced object (currently the ground plane) to the window.
fn drawShapeDisplay(shape: sshape.ElementRange, model: Mat4, color: Vec4) void {
    // Vertex-shader uniforms transform positions/normals and project the same
    // vertex into the shadow map so the fragment shader can test its shadow.
    const vs_params: shd.DisplayVsParams = .{
        .model = model,
        .mvp = Mat4.mul(model, state.view_proj),
        .light_mvp = Mat4.mul(model, state.light_view_proj),
        .diff_color = color,
    };

    // Fragment-shader uniforms describe the viewer and light. A fragment shader
    // runs for covered pixels and computes their final color/lighting.
    const fs_params: shd.DisplayFsParams = .{
        .eye_pos = state.camera.eye_pos,
        .light_dir = Vec3.normalized(state.light_pos),
    };
    var bindings: sg.Bindings = .{};
    bindings.vertex_buffers[0] = state.vbuf;
    bindings.index_buffer = state.ibuf;

    // The display shader reads the depth texture produced in pass 1.
    // A view selects how an image is used; a sampler controls filtering, wrapping,
    // and (here) depth comparison.
    bindings.views[shd.VIEW_shadow_map] = state.shadow.tex_view;
    bindings.samplers[shd.SMP_shadow_sampler] = state.shadow.sampler;
    sg.applyPipeline(state.display.pipeline);
    sg.applyBindings(bindings);
    sg.applyUniforms(shd.UB_display_vs_params, sg.asRange(&vs_params));
    sg.applyUniforms(shd.UB_display_fs_params, sg.asRange(&fs_params));

    // Instance count 1 means draw exactly one plane.
    sg.draw(@intCast(shape.base_element), @intCast(shape.num_elements), 1);
}

// Draw all boxes or all balls to the window with GPU instancing.
fn drawInstancedDisplay(shape: sshape.ElementRange, inst_buf: sg.Buffer, count: usize) void {
    if (count == 0) return;

    // Unlike the ground shader, the model transform and color come from each
    // instance record. These uniforms therefore contain only shared values.
    const vs_params: shd.DisplayInstVsParams = .{
        .view_proj = state.view_proj,
        .light_view_proj = state.light_view_proj,
        // The shader uses this flag to visualize whether bodies are sleeping.
        .awake_filter = if (state.ui.show_sleeping) 1.0 else 0.0,
    };
    const fs_params: shd.DisplayFsParams = .{
        .eye_pos = state.camera.eye_pos,
        .light_dir = Vec3.normalized(state.light_pos),
    };
    var bindings: sg.Bindings = .{};
    bindings.vertex_buffers[0] = state.vbuf;
    bindings.vertex_buffers[1] = inst_buf;
    bindings.index_buffer = state.ibuf;
    bindings.views[shd.VIEW_shadow_map] = state.shadow.tex_view;
    bindings.samplers[shd.SMP_shadow_sampler] = state.shadow.sampler;
    sg.applyPipeline(state.display.inst_pipeline);
    sg.applyBindings(bindings);
    sg.applyUniforms(shd.UB_display_inst_vs_params, sg.asRange(&vs_params));
    sg.applyUniforms(shd.UB_display_fs_params, sg.asRange(&fs_params));
    sg.draw(@intCast(shape.base_element), @intCast(shape.num_elements), @intCast(count));
}

//------------------------------------------------------------------------------
// Box3D simulation
//------------------------------------------------------------------------------

// Create a Box3D world and a large static ground body.
fn physicsInit() void {
    // Definition structs hold creation options. Starting from Box3D's defaults
    // makes any options not mentioned here explicit and safe.
    var world_def = b3.b3DefaultWorldDef();
    state.physics.world = b3.b3CreateWorld(&world_def);

    // A body owns position/rotation and one or more collision shapes. The default
    // body type is static, so gravity and impulses do not move the ground.
    var ground_body_def = b3.b3DefaultBodyDef();
    // The ground box is 20 units tall and centered at y=-10, placing its top at 0.
    ground_body_def.position = .{ .x = 0.0, .y = -10.0, .z = 0.0 };
    state.physics.ground = b3.b3CreateBody(state.physics.world, &ground_body_def);

    // Box3D hull creation uses half-extents: distance from center to each side.
    const half_size = ground_size * 0.5;
    var ground_box = b3.b3MakeBoxHull(half_size, 10.0, half_size);
    var ground_shape_def = b3.b3DefaultShapeDef();

    // Attach the collision hull to the body. The visible plane is separate GPU
    // geometry; Box3D never renders anything itself.
    _ = b3.b3CreateHullShape(state.physics.ground, &ground_shape_def, &ground_box.base);
}

// Convert one Box3D world transform into the compact format expected by the
// instanced vertex shaders.
fn copyInstanceTransform(instance: *InstanceData, transform: b3.b3WorldTransform) void {
    // Box3D stores orientation as a quaternion: four numbers representing a
    // rotation without the gimbal-lock problems of Euler angles.
    const rotation = Mat4.fromQuaternion(
        transform.q.v.x,
        transform.q.v.y,
        transform.q.v.z,
        transform.q.s,
    );
    // Translation moves the mesh from the origin to the body's world position.
    const translation = Mat4.translation(.{
        .x = transform.p.x,
        .y = transform.p.y,
        .z = transform.p.z,
    });

    // Combine rotation and translation. Transpose bridges this CPU matrix type's
    // convention with the row vectors laid out as shader vertex attributes.
    const matrix = Mat4.transpose(Mat4.mul(rotation, translation));

    // Upload only three rows; the shader reconstructs the affine transform.
    instance.xxxx = rowAsVec4(matrix.m[0]);
    instance.yyyy = rowAsVec4(matrix.m[1]);
    instance.zzzz = rowAsVec4(matrix.m[2]);
}

// Convert the math library's array representation into its named Vec4 fields.
fn rowAsVec4(row: [4]f32) Vec4 {
    return .{ .x = row[0], .y = row[1], .z = row[2], .w = row[3] };
}

// Advance physics and synchronize the bodies that moved back to render data.
fn physicsUpdate(frame_delta_sec: f64) void {
    // Rendering only contributes elapsed time. Box3D always receives the same
    // timestep, so changing refresh rate does not change the simulation step.
    state.physics.tick_accumulator_sec += frame_delta_sec;

    // Execute every complete fixed tick and retain the fractional remainder for
    // the next rendered frame. A fast frame may execute none; a slow frame may
    // execute several to catch the simulation up to elapsed real time.
    var world_step_time: u64 = 0;
    var copy_transforms_time: u64 = 0;
    var num_steps: i32 = 0;
    while (state.physics.tick_accumulator_sec >= physics_tick_sec) {
        var start = stm.now();
        b3.b3World_Step(
            state.physics.world,
            @floatCast(physics_tick_sec),
            physics_sub_step_count,
        );
        world_step_time += stm.since(start);

        // Body events belong to the most recent world step and are transient.
        // Consume them before another step replaces the event buffer.
        start = stm.now();
        copyBodyMoveEvents();
        copy_transforms_time += stm.since(start);

        state.physics.tick_accumulator_sec -= physics_tick_sec;
        num_steps += 1;
    }
    state.profiling.physics_world_step_time = world_step_time;
    state.profiling.copy_transforms_time = copy_transforms_time;
    state.profiling.world_steps_per_frame = num_steps;
    state.profiling.num_awake_bodies = b3.b3World_GetAwakeBodyCount(state.physics.world);

    // A sleeping body is at rest, so Box3D can skip solving it until something
    // wakes it. Encode awake/sleeping in alpha for the shader's debug coloring.
    if (state.ui.show_sleeping) {
        for (state.physics.bodies[0..state.physics.num_bodies]) |body| {
            const instance: *InstanceData = @ptrCast(@alignCast(b3.b3Body_GetUserData(body).?));
            instance.color.w = if (b3.b3Body_IsAwake(body)) 0.0 else 1.0;
        }
    }
}

// Box3D emits a cache-friendly move-event array after each world step. Consume
// it immediately because the data is transient and replaced by the next step.
fn copyBodyMoveEvents() void {
    const events = b3.b3World_GetBodyEvents(state.physics.world);
    for (0..@intCast(events.moveCount)) |index| {
        const event = &events.moveEvents[index];

        // userData points directly at this body's stable InstanceData record.
        // Recover that typed pointer and update the GPU-bound transform.
        const instance: *InstanceData = @ptrCast(@alignCast(event.userData.?));
        copyInstanceTransform(instance, event.transform);
    }
}

// Tiny deterministic pseudo-random generator. It is sufficient for varied demo
// colors/impulses; it is not suitable for security or cryptography.
fn xorshift32() u32 {
    random_state ^= random_state << 13;
    random_state ^= random_state >> 17;
    random_state ^= random_state << 5;
    return random_state;
}

// Turn three bytes of random bits into components in the range 0...1.
fn randomUnitVec3() Vec3 {
    const bits = xorshift32();
    return .{
        .x = @as(f32, @floatFromInt(bits & 255)) / 255.0,
        .y = @as(f32, @floatFromInt((bits >> 8) & 255)) / 255.0,
        .z = @as(f32, @floatFromInt((bits >> 16) & 255)) / 255.0,
    };
}

// Remap the 0...1 vector to -1...1 around the origin.
fn randomIntervalVec3() Vec3 {
    const v = randomUnitVec3();
    return Vec3.scale(.{ .x = v.x - 0.5, .y = v.y - 0.5, .z = v.z - 0.5 }, 2.0);
}

// Spawn one dynamic body, alternating between boxes and balls.
fn physicsAddBody() void {
    const index = state.physics.num_bodies;
    // Fixed storage is full; leave the existing simulation running.
    if (index >= max_shapes) return;

    // Alternating lets each shape type use its own tightly packed instance buffer.
    const is_box = (index & 1) == 0;
    const instance = if (is_box) blk: {
        const result = &state.instances.boxes[state.instances.num_boxes];
        state.instances.num_boxes += 1;
        break :blk result;
    } else blk: {
        const result = &state.instances.balls[state.instances.num_balls];
        state.instances.num_balls += 1;
        break :blk result;
    };

    // Dynamic bodies respond to gravity, collisions, and impulses.
    var body_def = b3.b3DefaultBodyDef();
    body_def.type = @intCast(b3.b3_dynamicBody);
    body_def.position = .{ .x = 0.0, .y = 15.0, .z = 0.0 };

    // Store a pointer to the render record on the physics body. Move events can
    // then update the correct record without a body-ID lookup table.
    body_def.userData = @ptrCast(instance);
    const body = b3.b3CreateBody(state.physics.world, &body_def);

    var shape_def = b3.b3DefaultShapeDef();
    // Density contributes to mass. Restitution controls bounciness: 0 is
    // inelastic, 1 preserves the normal collision speed.
    shape_def.density = 1.0;
    shape_def.baseMaterial.restitution = 0.25;
    if (is_box) {
        // The physics cube matches the dimensions of the visible cube mesh.
        var hull = b3.b3MakeCubeHull(box_size * 0.5);
        _ = b3.b3CreateHullShape(body, &shape_def, &hull.base);
    } else {
        // Rolling resistance gradually slows a sphere rolling over the ground.
        shape_def.baseMaterial.rollingResistance = 0.05;
        var sphere: b3.b3Sphere = .{ .radius = ball_radius };
        _ = b3.b3CreateSphereShape(body, &shape_def, &sphere);
    }

    // Keep the body handle for UI/debug queries and give this instance a stable,
    // deterministic random color.
    state.physics.bodies[index] = body;
    const color = randomUnitVec3();
    instance.color = .{ .x = color.x, .y = color.y, .z = color.z, .w = 1.0 };
    const transform = b3.b3Body_GetTransform(body);
    copyInstanceTransform(instance, transform);

    // Kick the body mostly upward with a little random sideways movement.
    // An impulse changes velocity immediately; it differs from a force applied
    // continuously over time.
    var random = randomIntervalVec3();
    const linear_impulse = Vec3.scale(
        Vec3.normalized(.{ .x = random.x, .y = random.y + 10.0, .z = random.z }),
        75.0,
    );
    b3.b3Body_ApplyLinearImpulseToCenter(body, toBox3dVec3(linear_impulse), true);

    // A separate angular impulse starts the object spinning.
    random = randomIntervalVec3();
    b3.b3Body_ApplyAngularImpulse(body, toBox3dVec3(Vec3.scale(random, 5.0)), true);
    state.physics.num_bodies += 1;
}

// The local and Box3D vector types have the same values but distinct Zig types.
fn toBox3dVec3(v: Vec3) b3.b3Vec3 {
    return .{ .x = v.x, .y = v.y, .z = v.z };
}

//------------------------------------------------------------------------------
// Graphics resource creation
//------------------------------------------------------------------------------
fn graphicsInit() void {
    // A single light illuminates the scene and defines the shadow viewpoint.
    state.light_pos = .{ .x = 50.0, .y = 100.0, .z = -75.0 };

    // A pass action says what should happen to render targets at pass start.
    // CLEAR replaces the previous frame with this sky-blue background.
    state.display.pass_action.colors[0] = .{
        .load_action = .CLEAR,
        .clear_value = .{ .r = 0.2, .g = 0.4, .b = 0.8, .a = 1.0 },
    };

    // Build all three meshes into temporary CPU arrays. The shape builder packs
    // them into one vertex buffer and one index buffer.
    //
    // Vertex buffer: attributes such as position and normal for each vertex.
    // Index buffer: integer references that reuse vertices to form triangles.
    var vertices: [sshape.max_vertex_size * 4096]u8 = undefined;
    var indices: [4096]u16 = undefined;
    var shape_builder: sshape.State = .{
        // Lighting needs positions and normals, but this shader does not use mesh
        // texture coordinates or per-vertex colors.
        .disable = .{ .texcoords = true, .colors = true },
        .vertices = .{ .buffer = sshape.asRange(&vertices) },
        .indices = .{ .buffer = sshape.asRange(&indices) },
    };

    // Each build call appends geometry. Save the resulting index range so later
    // draw calls can select just that shape from the shared buffers.
    sshape.buildPlane(&shape_builder, .{ .width = ground_size, .depth = ground_size });
    state.shapes.plane = sshape.elementRange(shape_builder);
    sshape.buildSphere(&shape_builder, .{
        .radius = ball_radius,
        .slices = 15,
        .stacks = 11,
    });
    state.shapes.ball = sshape.elementRange(shape_builder);
    sshape.buildBox(&shape_builder, .{
        .width = box_size,
        .height = box_size,
        .depth = box_size,
    });
    state.shapes.box = sshape.elementRange(shape_builder);

    // Upload the completed static geometry to GPU-owned buffers.
    state.vbuf = sg.makeBuffer(sshape.vertexBufferDesc(shape_builder));
    state.ibuf = sg.makeBuffer(sshape.indexBufferDesc(shape_builder));

    // The ground pipeline uses one model matrix supplied as a uniform.
    state.display.pipeline = sg.makePipeline(.{
        // sokol-shdc generated a shader variant for every enabled backend.
        // queryBackend chooses OpenGL, Metal, D3D11, WebGL, etc. at runtime.
        .shader = sg.makeShader(shd.displayShaderDesc(sg.queryBackend())),
        // Layout maps bytes in bound vertex buffers to shader input attributes.
        .layout = displayLayout(shape_builder),
        // Keep the nearest surface at each pixel and write new depth values.
        .depth = .{ .write_enabled = true, .compare = .LESS_EQUAL },
        // The shared index buffer stores 16-bit indices.
        .index_type = .UINT16,
        // Do not rasterize triangles facing away from the camera.
        .cull_mode = .BACK,
        // Labels appear in GPU debuggers and sokol-gfx's inspector.
        .label = "display-pipeline",
    });

    // The instanced display pipeline uses a related shader/layout which also
    // reads a transform and color from vertex-buffer slot 1.
    state.display.inst_pipeline = sg.makePipeline(.{
        .shader = sg.makeShader(shd.displayInstancedShaderDesc(sg.queryBackend())),
        .layout = displayInstancedLayout(shape_builder),
        .depth = .{ .write_enabled = true, .compare = .LESS_EQUAL },
        .index_type = .UINT16,
        .cull_mode = .BACK,
        .label = "display-instanced-pipeline",
    });

    // Create an off-screen image containing one depth value per shadow-map pixel.
    // It is not a normal color image; it is both a render attachment and later a
    // texture sampled by the display shader.
    const shadow_image = sg.makeImage(.{
        .usage = .{ .depth_stencil_attachment = true },
        .width = shadow_map_size,
        .height = shadow_map_size,
        .pixel_format = .DEPTH,
        .sample_count = 1,
        .label = "shadow-map-image",
    });

    // A texture view exposes the depth image for shader sampling.
    state.shadow.tex_view = sg.makeView(.{
        .texture = .{ .image = shadow_image },
        .label = "shadow-map-texview",
    });

    // Describe the off-screen pass. Clear old depth to the far value (1.0), draw
    // new depths, and STORE them because the next pass must read the result.
    state.shadow.pass = .{
        .action = .{ .depth = .{
            .load_action = .CLEAR,
            .store_action = .STORE,
            .clear_value = 1.0,
        } },
        .attachments = .{
            .depth_stencil = sg.makeView(.{
                .depth_stencil_attachment = .{ .image = shadow_image },
                .label = "shadow-map-dsview",
            }),
        },
        .label = "shadow-pass",
    };

    // A comparison sampler makes shadow testing convenient: sampled light depth
    // is compared with the current fragment's light-space depth. Linear filtering
    // softens the otherwise blocky edge slightly.
    state.shadow.sampler = sg.makeSampler(.{
        .min_filter = .LINEAR,
        .mag_filter = .LINEAR,
        .wrap_u = .CLAMP_TO_EDGE,
        .wrap_v = .CLAMP_TO_EDGE,
        .compare = .LESS,
        .label = "shadow-map-sampler",
    });

    // The shadow pipeline writes only depth. Front-face culling helps reduce
    // self-shadowing artifacts ("shadow acne") by rendering back faces instead.
    state.shadow.inst_pipeline = sg.makePipeline(.{
        .shader = sg.makeShader(shd.shadowInstancedShaderDesc(sg.queryBackend())),
        .layout = shadowInstancedLayout(shape_builder),
        .depth = .{
            .pixel_format = .DEPTH,
            .compare = .LESS_EQUAL,
            .write_enabled = true,
        },
        .index_type = .UINT16,
        .cull_mode = .FRONT,
        // The off-screen shadow image is not multisampled.
        .sample_count = 1,
        // Tell sokol that this pipeline has no color attachment.
        .colors = noColorTargets(),
        .label = "shadow-instanced-pipeline",
    });

    // Allocate streaming instance buffers at maximum capacity. `stream_update`
    // tells sokol they are expected to receive fresh data frequently.
    state.box_inst_buf = sg.makeBuffer(.{
        .usage = .{ .stream_update = true },
        .size = max_instances * @sizeOf(InstanceData),
        .label = "box-instance-buffer",
    });
    state.ball_inst_buf = sg.makeBuffer(.{
        .usage = .{ .stream_update = true },
        .size = max_instances * @sizeOf(InstanceData),
        .label = "ball-instance-buffer",
    });
}

// Describe the ground vertex layout: both attributes come from mesh buffer 0.
fn displayLayout(builder: sshape.State) sg.VertexLayoutState {
    var layout: sg.VertexLayoutState = .{};
    layout.buffers[0] = sshape.vertexBufferLayoutState(builder);
    layout.attrs[shd.ATTR_display_pos] = sshape.positionVertexAttrState(builder);
    layout.attrs[shd.ATTR_display_normal] = sshape.normalVertexAttrState(builder);
    return layout;
}

// Describe the visible instanced layout.
fn displayInstancedLayout(builder: sshape.State) sg.VertexLayoutState {
    var layout: sg.VertexLayoutState = .{};

    // Buffer 0 advances once per mesh vertex.
    layout.buffers[0] = sshape.vertexBufferLayoutState(builder);

    // Buffer 1 advances once per *instance*, so all vertices in one object see
    // the same transform/color record. Stride is the distance to the next record.
    layout.buffers[1] = .{
        .step_func = .PER_INSTANCE,
        .stride = @sizeOf(InstanceData),
    };

    // Position and normal come from the reusable mesh.
    layout.attrs[shd.ATTR_display_instanced_pos] = sshape.positionVertexAttrState(builder);
    layout.attrs[shd.ATTR_display_instanced_normal] = sshape.normalVertexAttrState(builder);

    // The remaining attributes are four Vec4 fields at byte offsets 0,16,32,48
    // inside InstanceData.
    layout.attrs[shd.ATTR_display_instanced_inst_xxxx] = instanceAttribute(0);
    layout.attrs[shd.ATTR_display_instanced_inst_yyyy] = instanceAttribute(16);
    layout.attrs[shd.ATTR_display_instanced_inst_zzzz] = instanceAttribute(32);
    layout.attrs[shd.ATTR_display_instanced_inst_color] = instanceAttribute(48);
    return layout;
}

// The shadow shader needs mesh positions and instance transforms, but no normals
// or colors because it outputs depth only.
fn shadowInstancedLayout(builder: sshape.State) sg.VertexLayoutState {
    var layout: sg.VertexLayoutState = .{};
    layout.buffers[0] = sshape.vertexBufferLayoutState(builder);
    layout.buffers[1] = .{
        .step_func = .PER_INSTANCE,
        .stride = @sizeOf(InstanceData),
    };
    layout.attrs[shd.ATTR_shadow_instanced_pos] = sshape.positionVertexAttrState(builder);
    layout.attrs[shd.ATTR_shadow_instanced_inst_xxxx] = instanceAttribute(0);
    layout.attrs[shd.ATTR_shadow_instanced_inst_yyyy] = instanceAttribute(16);
    layout.attrs[shd.ATTR_shadow_instanced_inst_zzzz] = instanceAttribute(32);
    return layout;
}

// Build one attribute descriptor for a Vec4 in instance-buffer slot 1.
fn instanceAttribute(offset: i32) sg.VertexAttrState {
    return .{ .format = .FLOAT4, .buffer_index = 1, .offset = offset };
}

// Pipeline color arrays have a fixed maximum size. Setting target 0 to NONE
// declares a depth-only pipeline while leaving unused entries at defaults.
fn noColorTargets() [8]sg.ColorTargetState {
    var colors: [8]sg.ColorTargetState = @splat(.{});
    colors[0].pixel_format = .NONE;
    return colors;
}

//------------------------------------------------------------------------------
// Debug UI
//------------------------------------------------------------------------------
fn drawUi() void {
    // Update sokol-app's inspector and begin an ImGui frame using current window
    // size, elapsed time, and high-DPI scale.
    sappimgui.trackFrame();
    simgui.newFrame(.{
        .width = sapp.width(),
        .height = sapp.height(),
        .delta_time = sapp.frameDuration(),
        .dpi_scale = sapp.dpiScale(),
    });

    // Add menus that expose live sokol_app and sokol_gfx state. These are useful
    // for learning which passes, pipelines, buffers, and draw calls exist.
    if (ig.igBeginMainMenuBar()) {
        sgimgui.drawMenu("sokol-gfx");
        sappimgui.drawMenu("sokol-app");
        ig.igEndMainMenuBar();
    }

    // Build the inspector windows themselves.
    sappimgui.draw();
    sgimgui.draw();

    // Position the demo's small translucent status panel on its first appearance.
    ig.igSetNextWindowPos(.{ .x = 30.0, .y = 50.0 }, ig.ImGuiCond_Once);
    ig.igSetNextWindowBgAlpha(0.5);
    const flags = ig.ImGuiWindowFlags_NoDecoration | ig.ImGuiWindowFlags_AlwaysAutoResize;
    if (ig.igBegin("Status", null, flags)) {
        // This checkbox modifies state directly; the instanced shader uses it to
        // reveal Box3D's sleeping-body optimization.
        _ = ig.igCheckbox("Show sleeping", &state.ui.show_sleeping);
        uiText("Total bodies: {d}", .{state.physics.num_bodies});
        uiText("Awake bodies: {d}", .{state.profiling.num_awake_bodies});
        uiText("World steps per frame: {d}", .{state.profiling.world_steps_per_frame});
        uiText("Solver sub-steps per world step: {d}", .{physics_sub_step_count});
        uiText("World Step Time: {d:.3}ms", .{stm.ms(state.profiling.physics_world_step_time)});
        uiText("Copy Transforms Time: {d:.3}ms", .{stm.ms(state.profiling.copy_transforms_time)});
    }
    ig.igEnd();
}

// ImGui's C function accepts a zero-terminated string. Format into a fixed stack
// buffer and ask Zig to append the sentinel byte, avoiding heap allocation.
fn uiText(comptime format: []const u8, args: anytype) void {
    var buffer: [128]u8 = undefined;
    const text = std.fmt.bufPrintSentinel(&buffer, format, args, 0) catch return;
    ig.igTextUnformatted(text.ptr);
}

//------------------------------------------------------------------------------
// Entry point
//------------------------------------------------------------------------------
pub fn main() void {
    // sokol_app owns the platform event loop. We give it callbacks and a portable
    // window description; it calls init once, frame repeatedly, input for events,
    // and cleanup at shutdown.
    sapp.run(.{
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = input,
        .width = 800,
        .height = 600,
        // Request 4x multisample anti-aliasing for smoother visible edges.
        .sample_count = 4,
        .window_title = "box3d-simple-sapp.c",
        .icon = .{ .sokol_default = true },
        .logger = .{ .func = slog.func },
    });
}
