"""Build the playable blockout extension in level/level.blend.

Run with:
  /home/dylan/blender/blender --background level/level.blend --python tools/author_level.py

The existing starting room is preserved.  Everything generated by this script
lives in named collections and can be regenerated without accumulating copies.
"""

from __future__ import annotations

import math
import os
import random

import bpy


ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BLEND_PATH = os.path.join(ROOT, "level", "level.blend")
GLB_PATH = os.path.join(ROOT, "level", "level.glb")
GENERATED_COLLECTIONS = (
    "Generated_Geometry",
    "Generated_Props",
    "Gameplay_Markers",
)

FLOOR_TOP = 1.0
FLOOR_DEPTH = 2.0
WALL_BOTTOM = FLOOR_TOP
WALL_HEIGHT = 5.0
WALL_CENTER_Z = WALL_BOTTOM + WALL_HEIGHT * 0.5
WALL_THICKNESS = 0.626
DOOR_WIDTH = 1.48
DOOR_HEIGHT = 2.65
DOOR_THICKNESS = 0.12
DOOR_CENTER_Z = FLOOR_TOP + DOOR_HEIGHT * 0.5


def material(name: str, rgba: tuple[float, float, float, float]):
    result = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    result.diffuse_color = rgba
    return result


MAT_GEO = material("Blockout Grey", (0.43, 0.44, 0.46, 1.0))
MAT_PROP = material("Prop Grey", (0.34, 0.35, 0.37, 1.0))
MAT_WHITE = material("Unlocked White", (0.973, 0.973, 0.949, 1.0))
MAT_PURPLE = material("Dracula Purple", (0.741, 0.576, 0.976, 1.0))
MAT_PINK = material("Dracula Pink", (1.0, 0.475, 0.776, 1.0))
MAT_CYAN = material("Dracula Cyan", (0.545, 0.914, 0.992, 1.0))
MAT_BLUE = material("Ammo Blue", (0.12, 0.43, 0.98, 1.0))
MAT_GREEN = material("Health Green", (0.12, 0.76, 0.30, 1.0))
MAT_ORANGE = material("Breakable Orange", (1.0, 0.42, 0.06, 1.0))


def remove_collection(name: str) -> None:
    collection = bpy.data.collections.get(name)
    if collection is None:
        return
    for obj in list(collection.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    bpy.data.collections.remove(collection)


for collection_name in GENERATED_COLLECTIONS:
    remove_collection(collection_name)


def new_collection(name: str):
    result = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(result)
    return result


GEO = new_collection("Generated_Geometry")
PROPS = new_collection("Generated_Props")
MARKERS = new_collection("Gameplay_Markers")
REFERENCE = bpy.data.collections.get("Authoring_Reference") or new_collection("Authoring_Reference")
REFERENCE.hide_render = True


def move_to_collection(obj, collection) -> None:
    for old in list(obj.users_collection):
        old.objects.unlink(obj)
    collection.objects.link(obj)


def cube(name, location, dimensions, mat=MAT_GEO, collection=GEO, rotation_z=0.0):
    bpy.ops.mesh.primitive_cube_add(location=location, rotation=(0.0, 0.0, rotation_z))
    obj = bpy.context.object
    obj.name = name
    obj.dimensions = dimensions
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    move_to_collection(obj, collection)
    if mat is not None:
        obj.data.materials.append(mat)
    return obj


def empty_cube(name, location, dimensions, collection=MARKERS):
    obj = bpy.data.objects.new(name, None)
    collection.objects.link(obj)
    obj.empty_display_type = "CUBE"
    obj.empty_display_size = 1.0
    obj.location = location
    obj.scale = (dimensions[0] * 0.5, dimensions[1] * 0.5, dimensions[2] * 0.5)
    return obj


def floor_box(name, min_x, max_x, min_y, max_y):
    return cube(
        name,
        ((min_x + max_x) * 0.5, (min_y + max_y) * 0.5, FLOOR_TOP - FLOOR_DEPTH * 0.5),
        (max_x - min_x, max_y - min_y, FLOOR_DEPTH),
    )


def wall_y(name, min_x, max_x, y):
    return cube(name, ((min_x + max_x) * 0.5, y, WALL_CENTER_Z), (max_x - min_x, WALL_THICKNESS, WALL_HEIGHT))


def wall_x(name, x, min_y, max_y):
    return cube(name, (x, (min_y + max_y) * 0.5, WALL_CENTER_Z), (WALL_THICKNESS, max_y - min_y, WALL_HEIGHT))


def doorway_y(prefix, min_x, max_x, y, center_x):
    gap_min = center_x - DOOR_WIDTH * 0.5 - 0.09
    gap_max = center_x + DOOR_WIDTH * 0.5 + 0.09
    wall_y(prefix + "_Left", min_x, gap_min, y)
    wall_y(prefix + "_Right", gap_max, max_x, y)
    lintel_height = WALL_HEIGHT - DOOR_HEIGHT
    cube(
        prefix + "_Lintel",
        (center_x, y, FLOOR_TOP + DOOR_HEIGHT + lintel_height * 0.5),
        (gap_max - gap_min, WALL_THICKNESS, lintel_height),
    )


def prop(name, location, dimensions, rotation_z=0.0):
    return cube(name, location, dimensions, MAT_PROP, PROPS, rotation_z)


def pickup(name, location, mat):
    return cube(name, location, (0.36, 0.36, 0.36), mat, MARKERS)


def breakable(index, location):
    return cube(f"Breakable_ItemBox_{index:02d}", location, (0.84, 0.84, 0.84), MAT_ORANGE, MARKERS)


def door(name, location, mat):
    return cube(name, location, (DOOR_WIDTH, DOOR_THICKNESS, DOOR_HEIGHT), mat, MARKERS)


# Keep the player scale guide in Blender without exporting it as level collision.
placeholder = bpy.data.objects.get("PlayerPlaceHolder")
if placeholder is not None:
    move_to_collection(placeholder, REFERENCE)
    placeholder.hide_render = True

# Remove the accidental exact duplicate cabinet from the original room.
duplicate = bpy.data.objects.get("Cube.010")
source = bpy.data.objects.get("Cube.009")
if duplicate is not None and source is not None:
    same_location = all(abs(a - b) < 0.0001 for a, b in zip(duplicate.location, source.location))
    same_dimensions = all(abs(a - b) < 0.0001 for a, b in zip(duplicate.dimensions, source.dimensions))
    if same_location and same_dimensions:
        bpy.data.objects.remove(duplicate, do_unlink=True)


# Floors: a cross hall, a loop around a solid storage island, and three rooms.
floor_box("Geo_Hall_Lower_Floor", -34.0, 34.0, 10.0, 17.0)
floor_box("Geo_Loop_West_Floor", -11.0, -7.0, 17.0, 31.0)
floor_box("Geo_Loop_East_Floor", 7.0, 11.0, 17.0, 31.0)
floor_box("Geo_Loop_North_Floor", -11.0, 11.0, 25.0, 31.0)
floor_box("Geo_Room_Purple_Floor", -26.0, -12.0, 17.0, 31.0)
floor_box("Geo_Room_Pink_Floor", -7.0, 7.0, 31.0, 45.0)
floor_box("Geo_Room_Cyan_Floor", 12.0, 26.0, 17.0, 31.0)

# A continuous ceiling seals the complete authored footprint. Its semantic
# prefix lets the runtime render it in the normal view while hiding it on the
# top-down map.
cube("Roof_Ceiling_All", (0.0, 17.0, 6.2), (68.7, 56.7, 0.4))

# Outer cross-hall walls leave the existing room's north doorway intact.
wall_y("Geo_Hall_South_West", -34.0, -13.25, 10.0)
wall_y("Geo_Hall_South_East", 13.25, 34.0, 10.0)
wall_x("Geo_Hall_West_End", -34.0, 10.0, 17.0)
wall_x("Geo_Hall_East_End", 34.0, 10.0, 17.0)
# Cap every north-facing dead-end edge of the cross hall. The room and loop
# floors continue north through the remaining spans.
wall_y("Geo_Hall_North_West_End", -34.0, -26.0, 17.0)
wall_y("Geo_Hall_North_West_Join", -12.0, -11.0, 17.0)
wall_y("Geo_Hall_North_East_Join", 11.0, 12.0, 17.0)
wall_y("Geo_Hall_North_East_End", 26.0, 34.0, 17.0)

# Locked rooms. Each room has exactly one corridor-facing colored door.
doorway_y("Geo_Purple_South", -26.0, -12.0, 17.0, -19.0)
wall_x("Geo_Purple_West", -26.0, 17.0, 31.0)
wall_x("Geo_Purple_East", -12.0, 17.0, 31.0)
wall_y("Geo_Purple_North", -26.0, -12.0, 31.0)

doorway_y("Geo_Cyan_South", 12.0, 26.0, 17.0, 19.0)
wall_x("Geo_Cyan_West", 12.0, 17.0, 31.0)
wall_x("Geo_Cyan_East", 26.0, 17.0, 31.0)
wall_y("Geo_Cyan_North", 12.0, 26.0, 31.0)

doorway_y("Geo_Pink_South", -7.0, 7.0, 31.0, 0.0)
wall_x("Geo_Pink_West", -7.0, 31.0, 45.0)
wall_x("Geo_Pink_East", 7.0, 31.0, 45.0)
wall_y("Geo_Pink_North", -7.0, 7.0, 45.0)

# Central loop boundaries and a solid storage/locker island.
wall_x("Geo_Loop_West_Outer", -11.0, 17.0, 31.0)
wall_x("Geo_Loop_East_Outer", 11.0, 17.0, 31.0)
wall_y("Geo_Loop_North_WestCap", -11.0, -7.0, 31.0)
wall_y("Geo_Loop_North_EastCap", 7.0, 11.0, 31.0)
cube("Geo_Central_Storage_Island", (0.0, 21.0, WALL_CENTER_Z), (14.0, 8.0, WALL_HEIGHT), MAT_PROP, GEO)

# Physics doors are authored meshes; their size and orientation become runtime data.
door("Door_Unlocked_Start", (0.03, 10.0, DOOR_CENTER_Z), MAT_WHITE)
door("Door_Locked_Purple_Archive", (-19.0, 17.0, DOOR_CENTER_Z), MAT_PURPLE)
door("Door_Locked_Pink_Records", (0.0, 31.0, DOOR_CENTER_Z), MAT_PINK)
door("Door_Locked_Cyan_Exit", (19.0, 17.0, DOOR_CENTER_Z), MAT_CYAN)

# Static furniture. The fixed seed keeps the authored scatter reproducible.
random.seed(0xD2A6_2026)
prop("Prop_Hall_West_Locker", (-28.0, 11.2, 2.65), (1.3, 0.8, 3.3))
prop("Prop_Hall_East_Locker", (28.0, 11.2, 2.65), (1.3, 0.8, 3.3))

# Purple archive room.
prop("Prop_Purple_Central_Table", (-19.0, 23.0, 1.65), (4.8, 1.5, 1.3))
prop("Prop_Purple_North_Desk", (-19.0, 28.2, 1.65), (3.8, 1.2, 1.3))
for index, y in enumerate((19.5, 22.5, 25.5, 28.5), 1):
    prop(f"Prop_Purple_West_Shelf_{index:02d}", (-24.8, y, 2.65), (0.8, 1.6, 3.3))
for index, y in enumerate((21.0, 25.0), 1):
    prop(f"Prop_Purple_East_Locker_{index:02d}", (-13.2, y, 2.65), (0.8, 1.4, 3.3))

# Pink records room.
prop("Prop_Pink_Table_West", (-3.5, 37.0, 1.65), (2.6, 1.3, 1.3))
prop("Prop_Pink_Table_East", (3.5, 37.0, 1.65), (2.6, 1.3, 1.3))
prop("Prop_Pink_Key_Table", (0.0, 41.5, 1.65), (3.0, 1.2, 1.3))
for index, x in enumerate((-5.7, -3.8, 3.8, 5.7), 1):
    prop(f"Prop_Pink_North_Cupboard_{index:02d}", (x, 43.8, 2.65), (1.3, 0.8, 3.3))

# Cyan ending room, with the far-center floor left clear for the trigger.
prop("Prop_Cyan_Workbench", (14.0, 23.0, 1.65), (1.2, 4.0, 1.3))
prop("Prop_Cyan_Low_Table", (21.5, 22.0, 1.55), (3.0, 1.4, 1.1))
for index, y in enumerate((19.5, 23.0, 26.5), 1):
    prop(f"Prop_Cyan_East_Locker_{index:02d}", (24.8, y, 2.65), (0.8, 1.4, 3.3))

# Strict key chain and resource placement.
pickup("Pickup_Key_Purple_01", (-4.0, 0.0, 2.30), MAT_PURPLE)
pickup("Pickup_Key_Pink_01", (-19.0, 28.2, 2.48), MAT_PINK)
pickup("Pickup_Key_Cyan_01", (0.0, 41.5, 2.48), MAT_CYAN)

ammo_positions = (
    (-1.0, 0.0, 2.30),
    (-31.8, 13.3, 1.18),
    (-22.0, 23.0, 2.48),
    (31.8, 13.3, 1.18),
    (3.5, 37.0, 2.48),
)
for index, location in enumerate(ammo_positions, 1):
    pickup(f"Pickup_Ammo_{index:02d}", location, MAT_BLUE)

health_positions = ((6.0, 5.5, 1.18), (-8.8, 28.5, 1.18), (21.5, 22.0, 2.28))
for index, location in enumerate(health_positions, 1):
    pickup(f"Pickup_Health_{index:02d}", location, MAT_GREEN)

for index, location in enumerate(
    (
        (-30.0, 15.7, 1.42),
        (30.0, 15.7, 1.42),
        (-14.2, 28.5, 1.42),
        (-5.5, 34.0, 1.42),
        (23.5, 28.5, 1.42),
    ),
    1,
):
    breakable(index, location)

# The typewriter remains a visible/collidable prop and doubles as its marker.
cube("Interactible_Typewriter_01", (-7.0, -7.0, 1.35), (0.9, 0.65, 0.70), MAT_PROP, MARKERS)
cube("Interactible_Typewriter_02", (-19.0, 23.0, 2.48), (0.9, 0.65, 0.70), MAT_PROP, MARKERS)
empty_cube("Trigger_SaveRoom_Start", (0.0, 0.0, 3.0), (17.0, 19.0, 4.0))
empty_cube("Trigger_SaveRoom_Purple", (-19.0, 24.0, 3.0), (13.0, 13.0, 4.0))
empty_cube("Trigger_Ending_01", (19.0, 28.0, 2.0), (5.0, 3.0, 2.0))

# Warm light markers use their X scale as the runtime radius.
for name, location, radius in (
    ("Light_Start", (0.0, 0.0, 5.2), 12.0),
    ("Light_Hall_West", (-22.0, 13.5, 5.2), 12.0),
    ("Light_Hall_East", (22.0, 13.5, 5.2), 12.0),
    ("Light_Purple", (-19.0, 24.0, 5.2), 11.0),
    ("Light_Pink", (0.0, 38.0, 5.2), 11.0),
    ("Light_Cyan", (19.0, 24.0, 5.2), 11.0),
    ("Light_Loop_West", (-9.0, 24.0, 5.0), 8.0),
    ("Light_Loop_East", (9.0, 24.0, 5.0), 8.0),
):
    light = bpy.data.objects.new(name, None)
    MARKERS.objects.link(light)
    light.empty_display_type = "SPHERE"
    light.empty_display_size = 0.35
    light.location = location
    light.scale = (radius, radius, radius)

# Move the hunter out of the starting room and into the lower hall.
hunter_spawn = bpy.data.objects.get("HunterSpawn")
if hunter_spawn is None:
    hunter_spawn = bpy.data.objects.new("HunterSpawn", None)
    MARKERS.objects.link(hunter_spawn)
else:
    move_to_collection(hunter_spawn, MARKERS)
hunter_spawn.location = (8.5, 15.0, FLOOR_TOP)
hunter_spawn.rotation_euler = (0.0, 0.0, math.radians(90.0))
hunter_spawn.empty_display_type = "ARROWS"
hunter_spawn.empty_display_size = 0.8

# Persist the editable scene, then export everything except authoring-only
# references. Selecting explicitly is reliable in headless Blender, whereas
# collection viewport/render visibility is not consistently honored by every
# glTF exporter version.
bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
bpy.ops.object.select_all(action="DESELECT")
reference_objects = set(REFERENCE.objects)
for scene_object in bpy.context.scene.objects:
    if scene_object not in reference_objects:
        scene_object.select_set(True)
bpy.ops.export_scene.gltf(
    filepath=GLB_PATH,
    export_format="GLB",
    use_selection=True,
    export_apply=False,
    export_yup=True,
)
print(f"Authored {BLEND_PATH}")
print(f"Exported {GLB_PATH}")
